### ISSUE TITLE
Path removing doesn't remove custom ones 

### ISSUE THREAD

**Issue by GamerKarl** [kwsch/NHSE#208]
Path removing doesn't remove custom ones from the terrain, just that, sorry for being annoying

**Comment by kwsch** [comment]
The custom paths aren't terrain, they're placed items.

**Comment by kwsch** [comment]
Looks like they're stored separately from the terrain/items:

https://github.com/Treeki/CylindricalEarth/blob/685a2b7f24816eb8da871736250399fc27e012af/savefile/save_schema_111_103_pseudoC.h#L1325-L1336

**Comment by dinosaw** [comment]
Apologies as I know this is older and closed. But I am running into this as well. Is there a way to remove the custom patterns applied to the pathing via NHSE? I ask because as the OP mentioned, some oddities occur. In my case, the pathing was removed  but not the custom patterns applied (which do not show as any type of item on the Field Item Editor). I had patterns going across areas you couldn't run, such as rivers. Using the terrain tool to remove and replace these spots work for the most part, but something built into NHSE would be great.

**Comment by kwsch** [comment]
@dinosaw the latest commits have a button for dealing with placed designs; you can clear/export/import them!

**Comment by dinosaw** [comment]
Hey @kwsch thanks for getting back so soon. In looking through the git logs, I'm assuming one of the following was the commit(s) you're referring to?

2670a6c751713aa1ed1c22c22aea4fdf11ca0bf6 Add placed design dump/load
0f451141c96ca54a11600d09b356158d49d329aa Add player house placed-item / flag editor
4d1bff38697cb7da79988efbfb5e0b2853eac61a Visually indicate dropped items instead of placed items

Using the text from those commits, I'm looking through the Field Item Editor and I can't seem to find where you can clear placed designs. I'm sure I'm just blind. Do you mind pointing me in the right direction?

**Comment by kwsch** [comment]
@dinosaw Field Item Editor => Terrain tab => Modify All button => bottom 3 options :)
