### ISSUE TITLE
"Watered"  flag doesn't actually water flowers

### ISSUE THREAD

**Issue by EdC94** [kwsch/NHSE#233]
Setting the "watered" flag on a flower on the field item map does not seem to actually water the flower, there is no sparkle once the save is restored and no hybrid/spread the next day.

**Comment by kwsch** [comment]
Did you also change the "Days Watered" value?

**Comment by EdC94** [comment]
Yes, i set it to 31 by clicking the Days label to get a "super-stud" flower, as the wiki says, but it doesn't seem to register in-game until i actually go and water the flower manually

**Comment by kwsch** [comment]
I was able to get rain on my game:

* A picked up flower had the Watered flag, and 0 days watered.
* A placed flower did not have the Watered flag, but had X days watered (different for certain patches of flowers less trafficked).

The key might be to not have the Watered flag if it's placed on the field.

**Comment by kwsch** [comment]
Closed due to lack of community research.

**Comment by CecilFF4** [comment]
I'd like to recommend this be re-opened on the basis that I've done some research on this that may prove beneficial.

I waited outside near some flowers that had not been watered. Once the game auto-saved, I watered three flowers in one particular acre (then backed it up), then saved and quit (and backed it up, too).

I dumped that acre (D3 in this example) from both saves and compared them. The files were identical. So the information for watering is not being dumped.

Then, I dumped the decrypted main.dat for both saves and did another hex compare. I found a few changes, some of which may be due to the clock changing, people moving, my quick-tool (d-pad right/left selection) changing... but there was one area of the files that changed where three bytes were all changed in that area from 0x00 to 0x60 in each case; these are the flowers being watered, IMO. The information is laid out below (again, all in acre D3):

Flower 1:
Location (108,122) = (0x6C,0x7A)

Flower 2:
Location (106,124) = (0x6A,0x7C)

Flower 3:
Location (108,124) = (0x6C,0x7C)

Offsets in decrypted main.dat:
Offset 1 = 0x00416168
Offset 2 = 0x0041617A
Offset 3 = 0x0041618C
All values changed from 0x00 to 0x60
All other values near these offsets were 0x00, possibly indicating these are field values that only indicate watering.

It's unknown which offset corresponds to which flower.

[watering dat.zip](https://github.com/kwsch/NHSE/files/4721137/watering.dat.zip)

**Comment by kwsch** [comment]
[SaveFg is at 0x415C08.
SaveFG is 0x928 sized; ends at 0x416530.](https://github.com/Treeki/CylindricalEarth/blob/master/savefile/save_schema_131080_131078_pseudoC.h#L1520)

```c
struct GSaveFg {                                   /* 0x928 big, align 4 */
  _7b9816fb                         _bc584dbe;                              // @0x0 size 0x900, align 1
  u16                               SpecialityFruit;                        // @0x900 size 0x2, align 2
  u16                               SisterFruit;                            // @0x902 size 0x2, align 2
  u32                               _e88f809d[8];                           // @0x904 size 0x4, align 4
  u8                                VillageFlower;                          // @0x924 size 0x1, align 1
  u8                                SpecialityFlower;                       // @0x925 size 0x1, align 1
};
```

Seems like `_bc584dbe` is a bitflag region which indicates if flowers at a given bit-index are watered or not. The "IsWatered" flag that an Item has is likely only for when it is picked up; things must be redirected to that bitflag array instead of when it is written to the field item list.
