### ISSUE TITLE
Flowers unable to be wrapped

### ISSUE THREAD

**Issue by JorVLP** [kwsch/NHSE#324]
The inventory editor doesn't correctly wrap flowers.

When loading an ACNH Poker .nhi file with wrapped flowers and then injecting into the game, the flowers are wrapped.
However if I copy that flower and place it in another spot in the inventory the flower is not wrapped.

**Comment by cpurules** [comment]
I wanted to add some more info to this since I am noticing other weird behavior with flowers.  This is while looking at the inventory/pockets, I've heard it functions similarly in the field editor as well.

(a) if I view a blank spot in my inventory, and then view a flower already in my inventory, there is no "wrapped" checkbox/dropdown:

![image](https://user-images.githubusercontent.com/52503242/89660941-0d6f8200-d8a0-11ea-870c-ecae44eefa46.png)

(b) if I view another item in my inventory, and then view a flower in my inventory, the "wrapped" settings _appear_ the same as the item I previously viewed:

![image](https://user-images.githubusercontent.com/52503242/89661077-37c13f80-d8a0-11ea-9805-479c6c184c33.png)
->
![image](https://user-images.githubusercontent.com/52503242/89661092-3d1e8a00-d8a0-11ea-9ee9-c7b9971f6968.png)

![image](https://user-images.githubusercontent.com/52503242/89661114-427bd480-d8a0-11ea-9507-b4af6eb09001.png)
->
![image](https://user-images.githubusercontent.com/52503242/89661129-47408880-d8a0-11ea-92f2-c7cc6e75472a.png)

![image](https://user-images.githubusercontent.com/52503242/89661145-4c9dd300-d8a0-11ea-8b99-1aa8ce3851ca.png)
->
![image](https://user-images.githubusercontent.com/52503242/89661164-51fb1d80-d8a0-11ea-9130-0504149e402f.png)

(c) in the cases where I am able to get the "wrapped" checkbox to appear for a flower (via point b above, or by choosing a flower from the item list dropdown), it seems that the wrapping doesn't actually apply in game.

Definitely a bug.
