### ISSUE TITLE
[META] Possible changes to how NHSE handles images.

### ISSUE THREAD

**Issue by berichan** [kwsch/NHSE#355]
This is a follow up to #354 but I thought I'd create a meta issue before creating a pull request because a lot of changes have been made D:

#### Proposition

![NHSE_2020-07-20_00-02-08](https://user-images.githubusercontent.com/66521620/87887683-1991bd80-ca1f-11ea-885a-f6319f5b0c81.png)

#### Changing PictureBox interpolation

This one is pretty basic, everything that's a picturebox is now an interpolating picturebox. The basic resize algorithm leaves a lot to be desired. NHSE.WinForms/Util/InterpolatingPictureBox.cs inherits from PictureBox and overrides the OnPaint function. Proof is in the pudding:

![NHSE_2020-07-19_23-17-35](https://user-images.githubusercontent.com/66521620/87886982-067bef00-ca19-11ea-9cdf-73e4de1e5c3c.png)

#### Item images

Firstly, I did a large PNGQuant pass on all images. Images look the same but the build size is smaller (from 8mb to 5mb) for a little less stress on the CI.

As said in #314 I created a very basic script to pull and rename all the files and batch convert them, falling back to MenuIcon images if no FtrIcon exists

Files look like this:
<details>
      <summary><b>Click here to view Windows Explorer image</b></summary>

![explorer_2020-07-19_23-33-34](https://user-images.githubusercontent.com/66521620/87887154-7dfe4e00-ca1a-11ea-9e5c-6e5913e01b68.png)

</details>

In [this comment](https://github.com/kwsch/NHSE/issues/314#issuecomment-647049768) I agree that auto-downloading/managing sprites is a pain. My new implementation does download+unzip images, but tries as best as possible to remove responsibility of item images.

The annotated image fetcher for your consideration

![annotated_img_fetcher](https://user-images.githubusercontent.com/66521620/87887613-adaf5500-ca1e-11ea-8be1-5530e29274c2.png)

Via menu strip

![NHSE_2020-07-20_00-16-59](https://user-images.githubusercontent.com/66521620/87887593-835d9780-ca1e-11ea-9f6c-d37dcb0ff43c.png)

The actual implementation doesn't have an image for each file, this is because many items reuse images, so instead a pointer file is created that tells NHSE which png name is used. This functionality overrides the existing ItemSprite.cs->FileLookup dictionary with my spritepointer file.

If all of this is a hard disagree, the path can be reverted to the application working directory path and we can once again ask users to get the images manually.

#### Others

The current bcsv parser causes some newlines/tabs because of four columns in itemparam.csv having 5-byte wide int-looking values, 0xE8C448B2, 0xFA71E75C, 0x42CD8039, 0x12D4D7A6 are the columns affected. I added a 5-byte long parse switch to ReadFieldUnknownType()

#### Closing note

All changes are ready for a pull request, a DevUtil ctrl+alt+D would probably need to be done first so the language strings are populated, this doesn't work on my PC, possibly because my paths have Japanese characters in them and my Windows locale is Japan, but the path gets corrupted no matter what I do.

https://github.com/berichan/NHSE-USB/tree/Auto

:3

**Comment by kwsch** [comment]
Sounds good ;)

I checked out the fork's code; some general comments I'd put in if it were a PR:

* The type refs for InterpolatingPictureBox don't have to be changed from PictureBox; `x is PictureBox` will still succeed, since the InterpolatingPictureBox inherits from PictureBox. The only place we'd use `InterpolatingPictureBox` explicitly is [here](https://github.com/kwsch/NHSE/compare/master...berichan:Auto#diff-723af6940b17d4d875a425f5dad0c0b3R64), when we create a new picturebox (where we say it's an interpolating one) ~~ all other locations don't need to know it's an InterpolatingPictureBox!
* Parsing: Odd that there's a 5byte typed value.
```cs
            var tmpBytes = new byte[8] { 0, 0, 0, 0, 0, 0, 0, 0 };
            Array.Copy(Data.Skip(offset).Take(5).ToArray(), 0, tmpBytes, 0, 5);
```
should be:
```cs
            var tmpBytes = new byte[8];
            Array.Copy(Data, offset, tmpBytes, 0, 5);
```
assuming it won't error out 
* Translations: Doesn't really need to be localized yet; will likely have it populate the next time I/anyone manually triggers it later.
* I generally stay away from hiding things in appdata; keeping things with a subfolder in the exe's directory makes it easier for people to uninstall / clean install new versions, and makes the operation of the program more transparent. Assuming it's for xplatform logic, then disregard, should be fine :)
* The Item id -> id could be read in as a dictionary and be used to remap the sprite request. Ideally, the item sprites would just be retrievable by $"{id:00000}_{cust}" with fallback (img doesn't exist) using cust = 0. The initial image packs were all filename'd English...

**Comment by berichan** [comment]
Got it! Not sure if I've been cursed by the world of Unity's mono implementation but it was the only c# I know and the compiler is guaranteed to fail on some platform unless I tell it exactly what I want, obviously don't have that problem here but the curse remains.

Appdata is for image portability mostly. No matter where the user "installs" NHSE the images are always available, so if the user downloads an update a few days after they don't have to manuall copy/paste images to working directory if they don't overwrite the first install. Also webclient doesn't have write access to working directory unless I change the directory permission manually (or run NHSE as admin), so it felt like the most usable solution.

Yes. For sprites, that's the most elegant solution so let's do that :)
