### ISSUE TITLE
Bulk Spawner Alphabetical order

### ISSUE THREAD

**Issue by obi1231941** [kwsch/NHSE#381]
Hello kurt I was wondering if you could add a feature where the bulk spawner spawns the diys in alphabetical order? Thank you

**Comment by kwsch** [comment]
Alphabetical order is specific to whatever language. Visitors aren't guaranteed to be using the same language.

Treasure islands are inferior to SysBot.AnimalCrossing automated islands.

**Comment by obi1231941** [comment]
Sysbot.AnimalCrossing automated island how do those work?

**Comment by kwsch** [comment]
If you're at all familiar with SysBot and its usage for Pokemon, SysBot.AnimalCrossing is a simple bot that receives commands to drop items on your island.

https://github.com/kwsch/SysBot.AnimalCrossing

You already have visitors arriving on your {treasure} island; why not let them just ask for whatever items they want instead of you wasting time speculating on what they'll want to pick up?

You provide the bot a "token" to log into discord, and people on your island can tell the bot to drop whatever item they ask, with no need to watch what they're doing.
