### ISSUE TITLE
dump all and load all designs

### ISSUE THREAD

**Issue by sir1st** [kwsch/NHSE#443]
very happy for using the nhse, and it would be really nice for designers if there is a dump all and load all designs in the map page. Wonder this can be realized in the next version? It would be really helpful, very thanks~

**Comment by kwsch** [comment]
Already exists; hold shift when clicking the import/export buttons.

**Comment by sir1st** [comment]
> Already exists; hold shift when clicking the import/export buttons.

very thanks, but only export buttons imply the shift function, import buttons doesn't support this.
if (ModifierKeys == Keys.Shift) in 
private void B_DumpDesign_Click(object sender, EventArgs e);
but not in 
private void B_LoadDesign_Click(object sender, EventArgs e)
which also means have to load one by one

**Comment by kwsch** [comment]
Done, I've added a bulk load for patterns & pro patterns 👍

**Comment by sir1st** [comment]
really appreciate that,

**Comment by kwsch** [comment]
I've updated the dump/load logic for patterns so that it also dumps an extra file with a different filename (using the index as a prefix).

I've also updated the field item editor so you can dump the map's placed pattern choices, via the Modify All button. The data could previously be cleared by the corresponding toolstripitem, and [corresponds to the MyDesignMap field in the savefile data](https://github.com/Treeki/CylindricalEarth/blob/48d524b8cb3282e22338a3cb2ca94fba074f42c4/savefile/save_schema_111_103_pseudoC.h#L1336).

**Comment by sir1st** [comment]
really appreciate this, thanks for your work and the nhse tool is more powerful, wow!
