### ISSUE TITLE
Problem with Give All Recipes

### ISSUE THREAD

**Issue by snailsimulator** [kwsch/NHSE#523]
when i give all recipes, i go in and see all the new notifications for the newly added recipes, but when i back out of the diy app it still shows a notification badge?

**Comment by kwsch** [comment]
You might not have been able to "see" the recipe in the menu to have the game acknowledge it as viewed once (no longer new). Try identifying which recipe(s) are the culprit?

**Comment by chaud-froid** [comment]
I got the same problem. I'm trying to search the "hidden" recipe(s) but I cant' found it/them :(

**Comment by TwistedHiccy** [comment]
I have the same issue as well, I've tried finding the responsible DIY items but no luck :/

**Comment by Zelfild** [comment]
Made an account just to pitch in the problem. I also suffered from this bug prior to patch 2.0 and here's how I worked around it.

The recipes responsible for this are Bridge Construction Kit and Campsite Construction Kit. Normally they are scripted to disappear from your DIY App if you have already crafted them, but if they get the New recipe flag with the Give All Recipes command the app will always show a red dot no matter what you do.

To fix the problem, what I did was:

1) Give All Recipes to my character
2) Restore the save file
3) Make sure all new recipes are acknowledged (this is where the bug rears its head as all it takes is to open the DIY App for all new recipes to register normal)
4) Back up the save and open it with NHSE
5) Search for Bridge Construction Kit and Campsite Construction Kit and uncheck the New flag.
6) Restore the save file and confirm the bug is gone.

A good work around for this would be to not have NHSE flag recipes given by the Give All Recipes option show up as new, or add an exception to Tom Nook's quest recipes.

**Comment by chaud-froid** [comment]
That's it indeed, thanks and I found an easier way.

1. give all recipe
2. search for "Bridge Construction Kit" and uncheck "known" (if you already do the quest in game because, it's gone when you did it) and "new"
3. Do it again for the "Campsite Construction Kit"
4. inject save

It's done. Also, If you use simply "craft all", the red dot never appears.

**Comment by Zelfild** [comment]
I gave a longer solution because I had at times the recipe show up as new even after unflagging it in the program, so your millage may vary. The Campsite Construction Kit is just three bytes bellow the Bridge Construction Kit so you can locate both rather quick after tracking either one of them.
