### ISSUE TITLE
question About netplayerID in main.dat

### ISSUE THREAD

**Issue by still1987** [kwsch/NHSE#556]
i want to know can get netplayerID  in main.dat by using NHSE!
and can i change netplayerID   by using NHSE?
thx a lot! appreciate your work!

**Comment by kwsch** [comment]
Refer to the issue templates.

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

**Comment by tallasd** [comment]
thx for reply!
i do this for my friends.
his island was hacked 
and he met a error code 2219-4301
i want to help him to connect the Internet 
and i think it relate to netplayerID 
and i find someboay find it 
https://github.com/Treeki/CylindricalEarth/blob/71d6581f288d8cf01e0ac467baf955f03ed0b680/savefile/save_schema_524421_524297_pseudoC.h#L254-L255

GSaveNetPlayerID                   NetPlayerID;                               // @0x25f10 size 0x58, align 8
i tried this on my decrypted main.dat file but find nothing except 0x0000
here is the calculation steps
GSaveNetPlayerID          NetPlayerID;                // @0x25f10 size 0x58, align 8   in GSavePlayerOther

 GSavePlayerOther          PlayerOther;                // @0x36a50 size 0x33ad0, align 16 in GSavePersonal

 GSavePersonal            GuestPlayers[8];              // @0x0 size 0x6a520, align 16 in GSaveLandOther

 GSaveLandOther           LandOther;                 // @0x547520 size 0x3aa690, align 16 in GSaveMain = Main.dat
547520 + 0 + 36a50 + 25f10 = 5a3e80

The problem is, after i calculate the real offset of something in the decrypted main.dat file and search that offset using binary editor, i can only found 0x0000 like this picture.
Is there something wrong in my operation?

![image](https://user-images.githubusercontent.com/17810762/142820052-db479bd6-d188-4819-93bd-59008a8eb6c0.png)
![image](https://user-images.githubusercontent.com/17810762/142820063-fbe6eec3-018c-49a0-9d4e-3bbf0cd8ed3d.png)


 i did use the same version of save files for acnh (2.0.0, for example) and the save_schema.h files.  And i checked the main file size, which is accorded with the struct GSaveMain { /* 0x8f1bb0 big, align 16 */)
