### ISSUE TITLE
What's the flag for activating the HHP thing?

### ISSUE THREAD

**Issue by VeninBallista** [kwsch/NHSE#625]
After editing my save with NHSE, none of the HHP things are visible, literally
Niko invites me to the supposed office but there's nothing there except an invicible place where you can sit on and so i can't progress on it... I also noticed that some of the letter designs at the airport are completely blank and take a while to download... Did I made a flag turn off or something?

And yes, I redownloaded the HHD DLC too to see if it was that but it wasn't...

**Comment by bbyglmrqz** [comment]
Hi there, we're experiencing the same problem, any fix you found? Thank you!

**Comment by berichan** [comment]
I'm closing this as stale. This is likely not related to a single flag but multiple issues caused by editing your save, if you or anyone else has anything else to add that could help with solving this then please post it here and I'll reopen this issue, but it seems this is unlikely to change without just restarting the save (NHSE has the ability to transfer your island data, all your items and villagers to a new save in any case)
