### ISSUE TITLE
Cannot use online after loading edited save.

### ISSUE THREAD

**Issue by jazziejazzgirl** [kwsch/NHSE#656]
I cannot use the online mode, but only specifically in animal crossing. Please help. I keep getting error 2219-4301. Every other game works online except this one. I know its something having to do with the save editor because the console isnt banned, if you restart you can connect online. Please help.

**Comment by berichan** [comment]
This seems to be caused by a mismatch of something stored server-side, you might have changed an immutable value that nintendo doesn't like that you've changed. https://github.com/kwsch/NHSE/issues/555

Either way, it's not something that NHSE would be able to solve. Just load your backup and see if that can still connect.
