### ISSUE TITLE
Stamp dates bugged after time traveling by editting activies?

### ISSUE THREAD

**Issue by sneedfeedseed** [kwsch/NHSE#72]
So I had my system clock set on the 20th then editted activities using the editor and time traveled 1 day later and on the 21st the dates I editted also change too here are some pictures

Before time traveling:
![KZPp](https://user-images.githubusercontent.com/62983327/79180845-f4b2fc00-7dd8-11ea-824a-5090a1526859.jpg)

and here's after:
![UXdx](https://user-images.githubusercontent.com/62983327/79180860-fe3c6400-7dd8-11ea-8a97-8a0a9623e6b6.jpg)

**Comment by kwsch** [comment]
The activity editing only reads values and writes the values back; it doesn't modify any date timestamps.

The activity timestamps aren't documented; I dunno what's going on with your timestamps (the Have a Nice DIY! didn't change date).

Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

Since we don't know where the activity timestamps are stored, we can't tell what is going on with your savedata timestamps :(
